// Strict per-sub-rank descriptions for "What Your Rank Means."
// Feedback is intentionally harsh — bad randoms are a reality, so the
// advice emphasises solo-carry potential, self-reliance, and not blaming
// teammates.
// Each entry also includes a `funny` one-liner for levity.

export const SUB_RANK_DESCRIPTIONS = {
  "Bronze I": {
    skill: "You're at the very start. Don't try to learn everything at once — pick one brawler and master their kit completely. Your game knowledge is minimal, and that's fine, but you need to put in the reps.",
    playstyle: "Stop chasing kills. You die because you walk into fights you can't win. Your randoms are bad — accept it and learn to survive on your own. Hold your lane, retreat when low, and stop expecting teammates to save you.",
    drafting: "Pick a brawler you can actually play, not one you think is 'meta.' A brawler you know beats a meta pick you can't use. Stop autolocking — wait and see what your team needs.",
    mechanics: "Turn off auto-aim. Practice manual aim until it's second nature. Stop dumping all three ammo at once — fire, reposition, fire again. Your movement is predictable; start using walls and bushes.",
    funny: "Welcome to the trenches. Your teammates think Gem Grab means 'grab gems and die with them.' You're not in elo hell — you ARE elo hell.",
  },
  "Bronze II": {
    skill: "You're starting to understand brawler abilities, but you still make fundamental mistakes. Focus on learning map layouts and where to position for each mode. One brawler, one map, one mode at a time.",
    playstyle: "You still chase kills instead of playing the objective. Your randoms won't help — learn to hold your lane alone. If you die, it's usually because you overextended. Recognize when you're outmatched and back off.",
    drafting: "You're picking based on preference, not strategy. Start paying attention to which brawlers work on which maps. Don't pick a sniper on a close-range map just because you like them.",
    mechanics: "Auto-aim is still your crutch. Break the habit now. Start holding your super for the right moment instead of firing it the instant it's charged. Use bushes to break line of sight.",
    funny: "You've graduated from 'completely lost' to 'mildly confused.' Your randoms still think Heist is a team deathmatch. Progress is progress.",
  },
  "Bronze III": {
    skill: "You know the basics but can't execute consistently. The gap between what you know and what you can do is wide. Close it by practicing, not by watching more videos.",
    playstyle: "You're starting to hold lanes but still get baited into bad fights. Your randoms will feed — that's not an excuse to give up. Learn to win your lane 1v1 so that even with bad teammates, you're not the weak link.",
    drafting: "You know some brawlers are better on certain maps but you still pick comfort over sense. Start actively choosing brawlers that fit the map and mode, not just your mood.",
    mechanics: "Manual aim is improving but inconsistent. Your ammo management is still reckless — you fire all three shots and then have nothing when the enemy pushes. Cycle your ammo: fire two, hold one.",
    funny: "You're the best player in Bronze. That's like being the tallest person in kindergarten. Enjoy it while it lasts — Silver is going to humble you.",
  },
  "Silver I": {
    skill: "You're grasping team comps and mode strategies, but execution lags behind. You know what to do; you just can't do it reliably yet. Stop blaming teammates and start fixing your own mistakes.",
    playstyle: "Your play is a mix of objective-focused and kill-chasing. Your randoms are inconsistent — some try, some don't. Learn to carry your weight regardless. If you lose your lane, your team loses the game. Win it.",
    drafting: "You're starting to think about counters but picks are still comfort-based. Start studying why certain brawlers are meta on certain maps, not just that they are.",
    mechanics: "Aim is improving. You're starting to use supers deliberately. But your gadget timing is still poor — you pop them reactively instead of proactively. Save gadgets for moments that matter.",
    funny: "Silver I — where everyone thinks they belong in Gold. Spoiler: most of you don't. Your randoms have discovered the uninstall button and they're not afraid to use it.",
  },
  "Silver II": {
    skill: "You understand the game better than most Bronze players, but you're still inconsistent. One good game doesn't mean you've improved — consistency is what separates Silver from Gold.",
    playstyle: "You hold lanes sometimes and chase kills other times. Pick a style and commit. Your randoms will let you down — learn to play around it. If your teammate feeds, don't tilt; compensate by winning harder on your side.",
    drafting: "You know counters exist but you don't use them consistently. Start memorizing 2-3 brawlers per mode so you always have a strong pick. Flexibility wins games.",
    mechanics: "Your aim is decent but your movement is still predictable. Start juking — change direction when the enemy fires. Use walls to peek and shoot instead of standing in the open.",
    funny: "You're in the 'I watch pros on YouTube but can't replicate anything' stage. Your mechanics say Bronze, your ego says Mythic. Reality says Silver II.",
  },
  "Silver III": {
    skill: "You're at the top of Silver and pushing for Gold. This is where many players plateau because they think they're better than they are. Stay humble, identify your weak spots, and grind them out.",
    playstyle: "You're starting to play objectives more consistently, but you still get pulled into unnecessary fights. Your randoms are still a coin flip — be the constant, not the variable. If you can consistently win your lane, you'll climb.",
    drafting: "Counter-drafting is emerging but it's not consistent. You sometimes pick into bad matchups because you're stubborn. Stop. If the enemy picks a tank, pick a tank-counter. It's not that hard.",
    mechanics: "Manual aim is now standard for you. Good. But your super timing is still off — you use it to confirm kills instead of creating space. A well-placed super zones enemies and wins objectives, not just one kill.",
    funny: "Almost Gold! Almost. Your randoms are auditioning for the world championship of feeding. They won't make it, but the dedication is admirable.",
  },
  "Gold I": {
    skill: "Solid fundamentals. You know which brawlers excel in which modes and you can read enemy comps. But 'solid' isn't 'good' — you need to start carrying games, not just contributing to them.",
    playstyle: "More objective-focused now. You hold lanes and retreat when low. But when your randoms feed — and they will — you need to learn to solo-carry. That means winning your lane so hard that it compensates for a weak teammate. Stop relying on others.",
    drafting: "Picks follow meta trends. Counter-drafting is emerging. But you still sometimes pick your 'main' into a bad matchup because you're comfortable. Comfort won't climb you past Gold. Adapt or stagnate.",
    mechanics: "Manual aim is standard. Supers are saved for key moments. But your ammo cycling needs work — you still panic-fire when pressured. Stay calm, hold your ammo, and shoot deliberately. Wall-peeking should be automatic by now.",
    funny: "Welcome to Gold, where everyone has a YouTube channel and zero tournament placements. Your randoms finally know what the objective is — they just choose to ignore it.",
  },
  "Gold II": {
    skill: "You're a competent player who understands the game. The problem is that 'competent' doesn't carry bad randoms. You need to be more than competent — you need to be the reason your team wins.",
    playstyle: "You hold lanes and play objectives, but you don't dominate. When your randoms are bad, you play safe and hope for the best. Stop hoping. Take control of the game — pressure your lane so hard the enemy collapses, creating space for even bad teammates to contribute.",
    drafting: "You know the meta but you don't always adapt to the enemy comp. If they have three tanks and you picked a thrower, that's on you. Start reading the enemy draft and countering it deliberately.",
    mechanics: "Your aim is good. Your super timing is decent. But your movement is still too linear. Start using unpredictable movement patterns — strafe, juke, and use terrain. A moving target is harder to hit; a predictable one is free damage for the enemy.",
    funny: "Gold II — the rank where you blame your randoms for everything. And you're... not entirely wrong. But you're also not entirely right. Touch grass, then touch ranked.",
  },
  "Gold III": {
    skill: "Top of Gold. You're better than most players you encounter, but you're not good enough to consistently carry bad teams. That's the barrier to Diamond — learning to hard-carry when your team is dead weight.",
    playstyle: "You play well when your team plays well. But when randoms feed, you crumble. Learn to win 1v2 situations. If you can't pressure two enemies at once, you're not ready for Diamond. Stop waiting for your team to make plays — make them yourself.",
    drafting: "Your picks are meta-aware but not always map-specific. A brawler can be meta and still be wrong for a particular map. Study map-specific tier lists and pick accordingly. Every pick should have a reason.",
    mechanics: "Aim, super timing, and ammo management are all solid. But you're not using gadgets strategically yet — you still pop them when you remember, not when they'd have maximum impact. Gadget usage is the difference between Gold and Diamond.",
    funny: "You're so close to Diamond you can taste it. It tastes like tears — yours, because your randoms just walked into the enemy 1v3 with 10 seconds left. Diamond awaits, if your sanity holds.",
  },
  "Diamond I": {
    skill: "Strong game sense. You read the flow of battle and track enemy supers. This is where ranked starts feeling like strategy. But your randoms are still a liability — learn to carry through decision-making, not just mechanics.",
    playstyle: "Disciplined and purposeful. But when your randoms feed — and at this level, they still do — you need to compensate harder. A Diamond player should be able to win their lane 1v1 every time. If you're not winning your lane consistently, you don't belong here yet.",
    drafting: "Counter-drafting is deliberate. Map-specific picks are common. But you need to think about team synergy, not just individual counters. A team of good individual picks with no synergy loses to a coordinated team of flex picks.",
    mechanics: "Precise aim, effective cover usage. Gadgets and supers are timed well. But your predictive aim needs work — you aim where the enemy is, not where they'll be. Start leading your shots. Practice against fast-moving targets.",
    funny: "Diamond I! You're officially 'good.' Your randoms are also officially 'good,' which makes it extra painful when they play like they bought the account. Welcome to the rank where you start questioning reality.",
  },
  "Diamond II": {
    skill: "You're a strong player who understands the game deeply. But understanding isn't enough — you need to execute under pressure. When your randoms collapse, can you still win? If not, you're not ready for Mythic.",
    playstyle: "You play disciplined, but you're too passive when your team falls behind. Bad randoms are not an excuse to play safe — they're a reason to play aggressive and create openings. If your team won't make plays, you have to. Stop waiting for the perfect moment; create it.",
    drafting: "Your draft is strong, but you sometimes get stubborn with your picks. If your preferred brawler got countered in draft, swallow your pride and flex. Ego loses games. Adaptability wins them.",
    mechanics: "Your mechanics are strong but not yet flawless. You still miss shots you shouldn't, and your super timing occasionally misfires. At this level, every missed shot matters. Tighten up your execution — there's no room for sloppy play.",
    funny: "Diamond II — the rank where you've memorized every excuse in the book. 'My randoms,' 'the matchup,' 'lag.' They're all valid. They're also all things Mythic players deal with too. Git gud.",
  },
  "Diamond III": {
    skill: "Top of Diamond. You're better than 90% of players, but the last 10% is where it gets brutal. Your randoms will be inconsistent, and the enemy will punish every mistake. You need near-flawless play to climb from here.",
    playstyle: "You're disciplined, but you need to learn to hard-carry. When your randoms feed, you need to win 1v2 or even 1v3 situations. That requires mechanical dominance and game sense that borders on prediction. If you can't solo-carry at Diamond III, you won't survive Mythic.",
    drafting: "Your draft is deliberate and map-specific. But you need to start thinking about draft-phase mind games — what will the enemy pick, and how do you counter it before they even lock in? Drafting is chess, not checkers.",
    mechanics: "Your aim is precise, your super timing is deliberate, and your ammo management is conscious. But your movement needs to be more deceptive. Start incorporating jukes, mind games, and unpredictable patterns. At this level, readable movement gets punished.",
    funny: "Ah, Diamond III. You are always getting soaked in tears because your randoms push you back to Diamond III, or you don't meet the requirements for Mythic (12 power 11s). You're stuck in the rank equivalent of a group project where you do all the work and still get a C.",
  },
  "Mythic I": {
    skill: "Advanced understanding. You have deep matchup knowledge and can track multiple cooldowns. But at Mythic, everyone knows the game — what separates you is execution and the ability to carry bad randoms against good enemies.",
    playstyle: "Highly coordinated — when your team cooperates. But randoms at Mythic can still be unreliable. You need to be able to take over games solo. If your teammate loses their lane, you need to win yours so hard that it doesn't matter. That's what Mythic requires.",
    drafting: "Full meta awareness. Your picks consider enemy comp, map, mode, and synergy. But you need to value flex picks more — being able to play multiple roles at a high level makes you invaluable in draft. One-tricks plateau at Mythic.",
    mechanics: "Excellent aim and movement. Super cycling and gadget timing are second nature. But your predictive aim needs to be sharper — you should be hitting shots on brawlers you can't even see yet, based on movement patterns. Read the enemy, don't react to them.",
    funny: "Mythic I! You finally made it. Now your randoms are good AND the enemies are good. The tears have been upgraded from 'Diamond sadness' to 'existential dread.' At least the card looks cool.",
  },
  "Mythic II": {
    skill: "You're well above average. Your game sense is sharp, your matchups are studied, and your execution is strong. But the gap between Mythic II and III is where casual players become serious ones. Are you ready to commit?",
    playstyle: "You pressure lanes intelligently and zone enemies away from objectives. But when your randoms collapse — and at this level, one bad teammate can lose the game — you need to be able to solo-carry against coordinated enemies. That means flawless positioning and zero wasted shots.",
    drafting: "Your draft considers everything. But you need to start innovating within the meta — surprise picks that catch the enemy off-guard can win games before they start. Just make sure your surprises are strategic, not reckless.",
    mechanics: "Near-flawless execution. But 'near' isn't enough at Mythic II. Every missed shot is a lost engagement. Every wasted super is a lost objective. Tighten your execution until it's mechanical — no thought, just reflex.",
    funny: "Mythic II — where every loss feels personal and every win feels like you got away with something. Your randoms are good now, which means when they mess up, it hurts more. Ignorance was bliss back in Gold.",
  },
  "Mythic III": {
    skill: "Top of Mythic. You're in the top fraction of players. Your randoms will be decent, but the enemy will be good. Every mistake is punished, every advantage is leveraged. You need to be flawless to push into Legendary.",
    playstyle: "Calculated aggression. Every move is intentional. But you still have moments where you hesitate or second-guess. At Mythic III, hesitation loses games. Commit to your reads — if you think the enemy is going to push, pre-fire and punish. Trust yourself.",
    drafting: "Expert-level drafting. You consider the full draft matrix. But you need to start thinking about bans strategically — not just banning the strongest brawler, but banning the brawler that would counter your planned comp. Draft manipulation is a skill.",
    mechanics: "Your mechanics are excellent, but you still have moments of inconsistency. A missed super at Mythic III can lose the game. Practice your mechanics until they're muscle memory — you should be able to execute perfectly under pressure without thinking.",
    funny: "Mythic III. You're so close to Legendary you can see it. It looks like a mirage made of your shattered hopes and your randoms' questionable life choices. The power 11 gate is behind you now — the only gate left is your own sanity.",
  },
  "Legendary I": {
    skill: "Near-expert game sense. You read the game several steps ahead and understand win conditions deeply. Very few players reach this level. But your randoms will still occasionally be bad — and at Legendary, bad randoms against good enemies means you need to be the difference-maker every single game.",
    playstyle: "Calculated and dominant. Every move serves a purpose. But when your randoms feed, you need to not just compensate — you need to actively take over the game. A Legendary player should be able to carry a 2v3 against good players. If you can't, you don't belong here.",
    drafting: "Expert-level drafting with full draft matrix consideration. Your draft often sets up the win before the match starts. But you need to stay humble — the meta shifts, and what worked last week might not work today. Keep studying.",
    mechanics: "Near-flawless. Pixel-perfect aim, advanced movement. But 'near-flawless' still means you make mistakes. At Legendary, one mistake can lose the game. Eliminate them. Your mechanics should be so consistent that errors are rare enough to be shocking.",
    funny: "Legendary I! You're officially in the 'I should be streaming this' rank. Your randoms are actually good now, which means you can't blame them anymore. We know, it hurts. Welcome to the rank where the only enemy left is yourself.",
  },
  "Legendary II": {
    skill: "You're elite. Your game sense is world-class, your decision-making is near-flawless, and your mechanics are sharp. But the climb to Legendary III and beyond requires perfection, not just excellence.",
    playstyle: "You dominate your lane and shape the flow of the match. But you still have moments where you rely on your team. At Legendary II, you should be able to solo-carry any game, regardless of your randoms. If you can't, you're not ready for the top.",
    drafting: "Your draft is masterful. You think in terms of team compositions and win conditions, not individual picks. But you need to start predicting enemy draft strategies and countering them before they materialize. Out-think the enemy, not just out-play them.",
    mechanics: "Flawless execution. Every shot, dodge, and super is intentional. But you need to push further — start incorporating advanced techniques that most players don't even know exist. Movement tech, super-cancel combos, ammo manipulation. Find edges wherever you can.",
    funny: "Legendary II. At this point, your randoms are better than 99% of players. When they mess up, it's not funny anymore — it's a statistical anomaly that ruins your day. You've started talking to your screen. The screen doesn't care.",
  },
  "Legendary III": {
    skill: "You're in the top 0.1% of players. Your game knowledge is encyclopedic, your decision-making is elite, and your mechanics are razor-sharp. The only thing standing between you and Masters is consistency under pressure.",
    playstyle: "You don't just win your lane — you win the game through it. Every decision is calculated, every movement optimized. But at Legendary III, the enemy is just as good as you. The difference-maker is who makes fewer mistakes. Be perfect.",
    drafting: "Professional-level draft strategy. You consider niche picks, surprise strategies, and draft-phase mind games. Your bans and picks tell a story. But the meta evolves constantly — what was optimal yesterday might be countered today. Never stop studying.",
    mechanics: "Your mechanics are among the best. But at Legendary III, everyone's mechanics are good. The difference is in the tiny details — one extra pixel of aim, one frame faster reaction, one smarter juke. Grind the micro-optimizations.",
    funny: "Legendary III. You're one step away from Masters. Your therapist knows about the randoms. Your family knows about the randoms. The randoms don't know they're the randoms. That's the cruelty of it.",
  },
  "Masters I": {
    skill: "Expert-level. Deep meta knowledge, exceptional game sense, and the ability to carry through sheer individual skill. You compete with the best. At this level, bad randoms are rare but still possible — and you should be able to win regardless.",
    playstyle: "Dominate-and-control. You dictate the pace, control engagements, and exploit every mistake. But Masters is where everyone is elite. The difference between winning and losing is who reads the game one step further. Be the one who's always one step ahead.",
    drafting: "Top-tier meta mastery. Every pick is optimized for the specific map, mode, and enemy comp. You know the meta inside out and can innovate within it. But don't get complacent — the meta shifts, and yesterday's innovation is today's standard.",
    mechanics: "Flawless. Every shot, dodge, and super is intentional and impactful. Your mechanical skill ceiling is among the highest in the game. But at Masters, mechanics don't win games — decision-making does. Focus on the macro, not just the micro.",
    funny: "Masters I! You made it. You're officially better than everyone you know in real life. Your randoms are now genuinely excellent, which means you've run out of excuses. It was never the randoms. It was always you. (It was still a little bit the randoms.)",
  },
  "Masters II": {
    skill: "You're among the best players in the world. Your game sense, mechanics, and decision-making are all elite. At this level, you're not just playing the game — you're shaping how it's played. But reaching Masters III requires pushing past your current ceiling.",
    playstyle: "You don't just win — you control the entire game. Your presence on a lane changes how the enemy plays. But at Masters II, the enemy can match you. The difference-maker is consistency — can you play at this level every single game, without a single off-game?",
    drafting: "You think in terms of meta innovation, not just meta adherence. Your draft choices put your team ahead before the first shot. But innovation is risky — make sure your surprises are calculated, not reckless. Every pick should have a reason and a backup plan.",
    mechanics: "Among the highest in the game. You execute plays that most players wouldn't attempt. But at Masters II, you need to focus on decision-making over mechanics — the right play at the right time beats a mechanically brilliant but strategically poor one.",
    funny: "Masters II. You've started analyzing your replays frame by frame. Your friends have stopped inviting you to things. 'One more game' has become your identity. The randoms are flawless now, and somehow you still find a way to blame them.",
  },
  "Masters III": {
    skill: "The top fraction of a percent. You're better than 99.9% of players. Your game knowledge, mechanics, and decision-making are all world-class. The only thing between you and Pro is the ability to perform flawlessly under maximum pressure, every game, without exception.",
    playstyle: "You dominate and control at a level most players will never reach. But at Masters III, the enemy is just as good. The difference between winning and losing is a single decision, a single shot, a single moment of hesitation. Be the one who doesn't hesitate.",
    drafting: "You're not just playing the meta — you're defining it. Your draft strategies are studied by other players. But the meta evolves, and what you innovate today will be countered tomorrow. Stay ahead of the curve or get left behind.",
    mechanics: "As close to perfect as humanly possible. Every mechanical skill is executed at the highest level. At Masters III, mechanics are a given — what wins games is the mental game. Read the enemy, predict their moves, and out-think them at every turn.",
    funny: "Masters III. You're so good that when you lose, people assume you were AFK. Your randoms are better than most people's entire friend list. The only thing left to fear is the ladder reset and your own declining reaction time. Tick tock.",
  },
  "Pro": {
    skill: "Professional / top-tier. You compete at the highest level. Game knowledge is encyclopedic and execution is elite. You are the meta — others study your play. This is the pinnacle of ranked competition, and anything less than perfection is a failure.",
    playstyle: "Tournament-level. Every decision is calculated, every movement optimized. Team coordination is seamless. You don't just play the game — you shape how it's played. Your game sense is world-class, and you should be able to carry any team, against any opponent, in any situation.",
    drafting: "Professional draft strategy. You consider the full competitive meta, including niche picks, surprise strategies, and draft-phase mind games. Your bans and picks tell a story and execute a plan. At this level, draft wins games before they start.",
    mechanics: "Perfection. Every mechanical skill is executed at the highest possible level. Movement, aim, and ability usage are all elite. You set the standard that others aspire to reach. Anything less than flawless execution is unacceptable at this level.",
    funny: "Pro rank. You've peaked. Not just in Brawl Stars — in life. There's nowhere to go from here but down. Every random is now a fan. Every loss is a scandal. Touch grass? You ARE the grass. Go join an eSports team before the rank decay gets you.",
  },
};